apiVersion: apps/v1
kind: Deployment
metadata:
  name: children-bank
  labels:
    app: children-bank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: children-bank
  template:
    metadata:
      labels:
        app: children-bank
    spec:
      containers:
        - name: children-bank
          image: smusaif94/children-bank:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
